### ISSUE TITLE
[jacobsen on 2007-06-01 15:53:51] : pDAQ build broken :-(

### ISSUE THREAD

**Issue by dglo** [dglo/pdaq#337]
DGlo: If this isn't you, assign it back to me and i'll hunt down the culprit... cheers,
JEJ

[INFO] ----------------------------------------------------------------------------
[INFO] Building daq-request-filler
[INFO]    task-segment: [clean, install]
[INFO] ----------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory /usr/local/pdaq/pDAQ_jacobsen/daq-request-filler/target
[INFO] Deleting directory /usr/local/pdaq/pDAQ_jacobsen/daq-request-filler/target/classes
[INFO] Deleting directory /usr/local/pdaq/pDAQ_jacobsen/daq-request-filler/target/test-classes
[INFO] [cobertura:clean {execution: clean}]
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:compile]
Compiling 4 source files to /usr/local/pdaq/pDAQ_jacobsen/daq-request-filler/target/classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/usr/local/pdaq/pDAQ_jacobsen/daq-request-filler/src/main/java/icecube/daq/reqFiller/StopMarker.java:[27,6] icecube.daq.reqFiller.StopMarker is not abstract and does not override abstract method writePayload(boolean,int,java.nio.ByteBuffer) in icecube.daq.payload.IWriteablePayload

**Comment by dglo** [comment]
[dglo on 2007-06-01 16:10:16]
Reverted the offending commit; there's a less disruptive way to do that
